# Site settings
email: wwwskylercom@hotmail.com
baseurl: ""
paginate: 10
paginate_path: "/blog/page-:num"
google_analytics:
encoding: utf-8

# SEO settings
title: Skyler Shi
description: >
  This is my personal website where you can check out my digital
  resume as well as the data analytics work I do.
url: ""
twitter_username: 
default_img: pictures/self6.jpeg

# Profile settings
name: Skyler Shi
profile_img: ../../../../pictures/self6.jpeg
project_img: ../../../../pictures/self6.jpeg
profile:
social:
  github: https://github.com/icarusoars

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
